### ISSUE TITLE
Add more details about Zero Order II

### ISSUE THREAD

**Issue by Tolsi** [donya/LittlefootProjects#1]
I very like this thing!
I'm not sure I understand how this works. I want more description so that anyone can use it meaningfully.
For example, I do not understand 4 screen, it somehow sets the melody. And the lower arrows are absolutely incomprehensible to me. Or can I reset it using some button or somehow?

**Comment by Tolsi** [comment]
Oh, it's some kind of touch piano is here on 4th screen. It would be great to have a simpler description, instruction or video than reading the code.

**Comment by donya** [comment]
There's a video of the system here: 
https://www.youtube.com/watch?v=8aeU_SwIH1g
The arrows are octave controls. 

This repository is primarily a personal workspace. Any large files that are for interactive compositions of mine (like Zero Order II) aren't really intended to serve as tutorials or to necessarily be intuitive to use. Basically the reason this repo is public is because GitHub didn't permit private repos for regular accounts at the time I created it.

**Comment by Tolsi** [comment]
I do not force you to do something, I just found it inspiring for myself and I think it would be great if it was more accessible. I did not know about the video, look. In any case, thanks for your work.
